/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.Item;
import model.Vendedor;

/**
 *
 * @author tadeu
 */
public class Comanda extends javax.swing.JFrame {
 Item gasComum = new Item();
    Item gasAditivada = new Item();
    Item oleoDisel = new Item();
    Item alcool = new Item();
    Item oleoMotor1 = new Item();
    Item oleoMotor500 = new Item();
    Vendedor posto = new Vendedor();
    posto.setCombustivel(oleoDisel);
    posto.setCombustivel(gasComum);
    posto.setCombustivel(gasAditivada);
    posto.setCombustivel(alcool);
    posto.setOleoMotor(oleoMotor500);
    posto.setOleoMotor(oleoMotor1);
    /**
     * Creates new form Comanda
     */
    public Comanda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup GrupoRadioAbastecimento = new javax.swing.ButtonGroup();
        javax.swing.ButtonGroup GrupoRadioPagamento = new javax.swing.ButtonGroup();
        javax.swing.JPanel PainelPrecoOleo = new javax.swing.JPanel();
        javax.swing.JLabel LabelOleo1 = new javax.swing.JLabel();
        javax.swing.JLabel LabelOleo500 = new javax.swing.JLabel();
        javax.swing.JTextField InputPrecoOleo500 = new javax.swing.JTextField();
        javax.swing.JTextField InputPrecoOleo1 = new javax.swing.JTextField();
        javax.swing.JPanel PainelPrecoCombustive = new javax.swing.JPanel();
        javax.swing.JLabel LabelOleoDisel = new javax.swing.JLabel();
        javax.swing.JLabel LabelGasComum = new javax.swing.JLabel();
        javax.swing.JLabel LabelGasAditivada = new javax.swing.JLabel();
        javax.swing.JLabel LabelAlcool = new javax.swing.JLabel();
        javax.swing.JTextField InputPrecoOleoDisel = new javax.swing.JTextField();
        javax.swing.JTextField InputPrecoGasComum = new javax.swing.JTextField();
        javax.swing.JTextField InputPrecoGasAditivada = new javax.swing.JTextField();
        javax.swing.JTextField InputPrecoAlcool = new javax.swing.JTextField();
        javax.swing.JPanel PainelPagamento = new javax.swing.JPanel();
        javax.swing.JButton BotaoObservacao = new javax.swing.JButton();
        javax.swing.JRadioButton RadioAvista = new javax.swing.JRadioButton();
        javax.swing.JRadioButton RadioPrazo = new javax.swing.JRadioButton();
        javax.swing.JLabel LabelTotalVenda = new javax.swing.JLabel();
        javax.swing.JTextField InputTotalVenda = new javax.swing.JTextField();
        javax.swing.JLabel LabelDiasPrazo = new javax.swing.JLabel();
        javax.swing.JTextField InputDiasPrazo = new javax.swing.JTextField();
        javax.swing.JPanel PainelAbastecimento = new javax.swing.JPanel();
        javax.swing.JRadioButton RadioOleoDisel = new javax.swing.JRadioButton();
        javax.swing.JRadioButton RadioGasComum = new javax.swing.JRadioButton();
        javax.swing.JRadioButton RadioAlcool = new javax.swing.JRadioButton();
        javax.swing.JRadioButton RadioGasAditivada = new javax.swing.JRadioButton();
        javax.swing.JLabel LabelTotalCombustivelVenda = new javax.swing.JLabel();
        javax.swing.JLabel LabelQuantidadeCombustivelVenda = new javax.swing.JLabel();
        javax.swing.JTextField InputQuantidadeVendaCombustivel = new javax.swing.JTextField();
        javax.swing.JTextField InputValorTotalVendaCombustivel = new javax.swing.JTextField();
        javax.swing.JPanel PainelCompraOleo = new javax.swing.JPanel();
        javax.swing.JTextField InputQuantidadeOleo1Venda = new javax.swing.JTextField();
        javax.swing.JTextField InputQuantidadeOleo500Venda = new javax.swing.JTextField();
        javax.swing.JTextField InputPrecoOleo500Venda = new javax.swing.JTextField();
        javax.swing.JTextField InputPrecoOleo1Venda = new javax.swing.JTextField();
        javax.swing.JLabel LabelTotalPrecoVendaOleo = new javax.swing.JLabel();
        javax.swing.JTextField InputTotalPrecoOleo = new javax.swing.JTextField();
        javax.swing.JCheckBox CheckBoxOleo500Venda = new javax.swing.JCheckBox();
        javax.swing.JCheckBox CheckBoxOleo1Venda = new javax.swing.JCheckBox();
        javax.swing.JLabel LabelQuantidadeOleosVenda = new javax.swing.JLabel();
        javax.swing.JLabel LabelEspeciePrecoVendaOleo = new javax.swing.JLabel();
        javax.swing.JPanel PainelBotoes = new javax.swing.JPanel();
        javax.swing.JButton BotaoCalcular = new javax.swing.JButton();
        javax.swing.JButton BotaoNovo = new javax.swing.JButton();
        javax.swing.JButton BotaoFexar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gui/Bundle"); // NOI18N
        PainelPrecoOleo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("Comanda.PainelPrecoOleo.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Code", 1, 12))); // NOI18N

        LabelOleo1.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelOleo1.setText(bundle.getString("Comanda.LabelOleo1.text")); // NOI18N

        LabelOleo500.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelOleo500.setText(bundle.getString("Comanda.LabelOleo500.text")); // NOI18N

        InputPrecoOleo500.setText(bundle.getString("Comanda.InputPrecoOleo500.text")); // NOI18N
        InputPrecoOleo500.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputPrecoOleo500KeyTyped(evt);
            }
        });

        InputPrecoOleo1.setText(bundle.getString("Comanda.InputPrecoOleo1.text")); // NOI18N
        InputPrecoOleo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputPrecoOleo1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PainelPrecoOleoLayout = new javax.swing.GroupLayout(PainelPrecoOleo);
        PainelPrecoOleo.setLayout(PainelPrecoOleoLayout);
        PainelPrecoOleoLayout.setHorizontalGroup(
            PainelPrecoOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrecoOleoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPrecoOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelOleo500)
                    .addComponent(LabelOleo1))
                .addGap(18, 18, 18)
                .addGroup(PainelPrecoOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputPrecoOleo500, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputPrecoOleo1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        PainelPrecoOleoLayout.setVerticalGroup(
            PainelPrecoOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrecoOleoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPrecoOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelOleo500)
                    .addComponent(InputPrecoOleo500, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelPrecoOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPrecoOleo1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelOleo1))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        PainelPrecoCombustive.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("Comanda.PainelPrecoCombustive.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Code", 1, 12))); // NOI18N

        LabelOleoDisel.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelOleoDisel.setText(bundle.getString("Comanda.LabelOleoDisel.text")); // NOI18N

        LabelGasComum.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelGasComum.setText(bundle.getString("Comanda.LabelGasComum.text")); // NOI18N

        LabelGasAditivada.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelGasAditivada.setText(bundle.getString("Comanda.LabelGasAditivada.text")); // NOI18N

        LabelAlcool.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelAlcool.setText(bundle.getString("Comanda.LabelAlcool.text")); // NOI18N

        InputPrecoOleoDisel.setText(bundle.getString("Comanda.InputPrecoOleoDisel.text")); // NOI18N
        InputPrecoOleoDisel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPrecoOleoDiselActionPerformed(evt);
            }
        });
        InputPrecoOleoDisel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputPrecoOleoDiselKeyTyped(evt);
            }
        });

        InputPrecoGasComum.setText(bundle.getString("Comanda.InputPrecoGasComum.text")); // NOI18N
        InputPrecoGasComum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputPrecoGasComumKeyTyped(evt);
            }
        });

        InputPrecoGasAditivada.setText(bundle.getString("Comanda.InputPrecoGasAditivada.text")); // NOI18N
        InputPrecoGasAditivada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputPrecoGasAditivadaKeyTyped(evt);
            }
        });

        InputPrecoAlcool.setText(bundle.getString("Comanda.InputPrecoAlcool.text")); // NOI18N
        InputPrecoAlcool.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputPrecoAlcoolKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PainelPrecoCombustiveLayout = new javax.swing.GroupLayout(PainelPrecoCombustive);
        PainelPrecoCombustive.setLayout(PainelPrecoCombustiveLayout);
        PainelPrecoCombustiveLayout.setHorizontalGroup(
            PainelPrecoCombustiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrecoCombustiveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPrecoCombustiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelOleoDisel)
                    .addComponent(LabelGasAditivada)
                    .addComponent(LabelGasComum)
                    .addComponent(LabelAlcool))
                .addGap(18, 18, 18)
                .addGroup(PainelPrecoCombustiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputPrecoOleoDisel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputPrecoGasComum, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputPrecoGasAditivada, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputPrecoAlcool, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        PainelPrecoCombustiveLayout.setVerticalGroup(
            PainelPrecoCombustiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrecoCombustiveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPrecoCombustiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PainelPrecoCombustiveLayout.createSequentialGroup()
                        .addComponent(InputPrecoOleoDisel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelPrecoCombustiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputPrecoGasComum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelGasComum))
                        .addGap(28, 28, 28))
                    .addGroup(PainelPrecoCombustiveLayout.createSequentialGroup()
                        .addComponent(LabelOleoDisel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PainelPrecoCombustiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputPrecoGasAditivada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelGasAditivada))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(PainelPrecoCombustiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPrecoAlcool, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAlcool))
                .addContainerGap())
        );

        PainelPagamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("Comanda.PainelPagamento.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Code", 1, 12))); // NOI18N

        BotaoObservacao.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        BotaoObservacao.setText(bundle.getString("Comanda.BotaoObservacao.text")); // NOI18N

        GrupoRadioPagamento.add(RadioAvista);
        RadioAvista.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        RadioAvista.setSelected(true);
        RadioAvista.setText(bundle.getString("Comanda.RadioAvista.text")); // NOI18N

        GrupoRadioPagamento.add(RadioPrazo);
        RadioPrazo.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        RadioPrazo.setText(bundle.getString("Comanda.RadioPrazo.text")); // NOI18N
        RadioPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioPrazoActionPerformed(evt);
            }
        });

        LabelTotalVenda.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelTotalVenda.setText(bundle.getString("Comanda.LabelTotalVenda.text")); // NOI18N

        InputTotalVenda.setEditable(false);
        InputTotalVenda.setText(bundle.getString("Comanda.InputTotalVenda.text")); // NOI18N

        LabelDiasPrazo.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelDiasPrazo.setText(bundle.getString("Comanda.LabelDiasPrazo.text")); // NOI18N

        InputDiasPrazo.setEditable(false);
        InputDiasPrazo.setText(bundle.getString("Comanda.InputDiasPrazo.text")); // NOI18N
        InputDiasPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDiasPrazoActionPerformed(evt);
            }
        });
        InputDiasPrazo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputDiasPrazoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PainelPagamentoLayout = new javax.swing.GroupLayout(PainelPagamento);
        PainelPagamento.setLayout(PainelPagamentoLayout);
        PainelPagamentoLayout.setHorizontalGroup(
            PainelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPagamentoLayout.createSequentialGroup()
                        .addComponent(RadioAvista)
                        .addGap(95, 95, 95)
                        .addComponent(RadioPrazo)
                        .addGap(56, 56, 56)
                        .addComponent(LabelDiasPrazo)
                        .addGap(18, 18, 18)
                        .addComponent(InputDiasPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPagamentoLayout.createSequentialGroup()
                        .addComponent(LabelTotalVenda)
                        .addGap(18, 18, 18)
                        .addGroup(PainelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotaoObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(InputTotalVenda))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelPagamentoLayout.setVerticalGroup(
            PainelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RadioAvista)
                        .addComponent(RadioPrazo))
                    .addComponent(InputDiasPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelPagamentoLayout.createSequentialGroup()
                        .addComponent(LabelDiasPrazo)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(PainelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(InputTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelPagamentoLayout.createSequentialGroup()
                        .addComponent(LabelTotalVenda)
                        .addGap(6, 6, 6)))
                .addGap(18, 18, 18)
                .addComponent(BotaoObservacao)
                .addGap(29, 29, 29))
        );

        PainelAbastecimento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("Comanda.PainelAbastecimento.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Code", 1, 12))); // NOI18N

        GrupoRadioAbastecimento.add(RadioOleoDisel);
        RadioOleoDisel.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        RadioOleoDisel.setSelected(true);
        RadioOleoDisel.setText(bundle.getString("Comanda.RadioOleoDisel.text")); // NOI18N

        GrupoRadioAbastecimento.add(RadioGasComum);
        RadioGasComum.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        RadioGasComum.setText(bundle.getString("Comanda.RadioGasComum.text")); // NOI18N
        RadioGasComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioGasComumActionPerformed(evt);
            }
        });

        GrupoRadioAbastecimento.add(RadioAlcool);
        RadioAlcool.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        RadioAlcool.setText(bundle.getString("Comanda.RadioAlcool.text")); // NOI18N
        RadioAlcool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAlcoolActionPerformed(evt);
            }
        });

        GrupoRadioAbastecimento.add(RadioGasAditivada);
        RadioGasAditivada.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        RadioGasAditivada.setText(bundle.getString("Comanda.RadioGasAditivada.text")); // NOI18N
        RadioGasAditivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioGasAditivadaActionPerformed(evt);
            }
        });

        LabelTotalCombustivelVenda.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelTotalCombustivelVenda.setText(bundle.getString("Comanda.LabelTotalCombustivelVenda.text")); // NOI18N

        LabelQuantidadeCombustivelVenda.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelQuantidadeCombustivelVenda.setText(bundle.getString("Comanda.LabelQuantidadeCombustivelVenda.text")); // NOI18N

        InputQuantidadeVendaCombustivel.setText(bundle.getString("Comanda.InputQuantidadeVendaCombustivel.text")); // NOI18N
        InputQuantidadeVendaCombustivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputQuantidadeVendaCombustivelKeyTyped(evt);
            }
        });

        InputValorTotalVendaCombustivel.setEditable(false);
        InputValorTotalVendaCombustivel.setText(bundle.getString("Comanda.InputValorTotalVendaCombustivel.text")); // NOI18N
        InputValorTotalVendaCombustivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputValorTotalVendaCombustivelKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PainelAbastecimentoLayout = new javax.swing.GroupLayout(PainelAbastecimento);
        PainelAbastecimento.setLayout(PainelAbastecimentoLayout);
        PainelAbastecimentoLayout.setHorizontalGroup(
            PainelAbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAbastecimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelAbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelAbastecimentoLayout.createSequentialGroup()
                        .addComponent(RadioOleoDisel)
                        .addGap(95, 95, 95)
                        .addComponent(RadioGasComum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(RadioGasAditivada)
                        .addGap(102, 102, 102)
                        .addComponent(RadioAlcool)
                        .addGap(90, 90, 90))
                    .addGroup(PainelAbastecimentoLayout.createSequentialGroup()
                        .addGroup(PainelAbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelQuantidadeCombustivelVenda)
                            .addComponent(LabelTotalCombustivelVenda))
                        .addGap(18, 18, 18)
                        .addGroup(PainelAbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputQuantidadeVendaCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputValorTotalVendaCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PainelAbastecimentoLayout.setVerticalGroup(
            PainelAbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAbastecimentoLayout.createSequentialGroup()
                .addGroup(PainelAbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioOleoDisel)
                    .addComponent(RadioGasComum)
                    .addComponent(RadioGasAditivada)
                    .addComponent(RadioAlcool))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelAbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PainelAbastecimentoLayout.createSequentialGroup()
                        .addComponent(InputQuantidadeVendaCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelAbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputValorTotalVendaCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTotalCombustivelVenda)))
                    .addGroup(PainelAbastecimentoLayout.createSequentialGroup()
                        .addComponent(LabelQuantidadeCombustivelVenda)
                        .addGap(34, 34, 34)))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        PainelCompraOleo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("Comanda.PainelCompraOleo.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Code", 1, 12))); // NOI18N

        InputQuantidadeOleo1Venda.setEditable(false);
        InputQuantidadeOleo1Venda.setText(bundle.getString("Comanda.InputQuantidadeOleo1Venda.text")); // NOI18N
        InputQuantidadeOleo1Venda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputQuantidadeOleo1VendaKeyTyped(evt);
            }
        });

        InputQuantidadeOleo500Venda.setEditable(false);
        InputQuantidadeOleo500Venda.setText(bundle.getString("Comanda.InputQuantidadeOleo500Venda.text")); // NOI18N
        InputQuantidadeOleo500Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputQuantidadeOleo500VendaActionPerformed(evt);
            }
        });
        InputQuantidadeOleo500Venda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputQuantidadeOleo500VendaKeyTyped(evt);
            }
        });

        InputPrecoOleo500Venda.setEditable(false);
        InputPrecoOleo500Venda.setText(bundle.getString("Comanda.InputPrecoOleo500Venda.text")); // NOI18N

        InputPrecoOleo1Venda.setEditable(false);
        InputPrecoOleo1Venda.setText(bundle.getString("Comanda.InputPrecoOleo1Venda.text")); // NOI18N

        LabelTotalPrecoVendaOleo.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelTotalPrecoVendaOleo.setText(bundle.getString("Comanda.LabelTotalPrecoVendaOleo.text")); // NOI18N

        InputTotalPrecoOleo.setEditable(false);
        InputTotalPrecoOleo.setText(bundle.getString("Comanda.InputTotalPrecoOleo.text")); // NOI18N

        CheckBoxOleo500Venda.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        CheckBoxOleo500Venda.setText(bundle.getString("Comanda.CheckBoxOleo500Venda.text")); // NOI18N
        CheckBoxOleo500Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxOleo500VendaActionPerformed(evt);
            }
        });

        CheckBoxOleo1Venda.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        CheckBoxOleo1Venda.setText(bundle.getString("Comanda.CheckBoxOleo1Venda.text")); // NOI18N
        CheckBoxOleo1Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxOleo1VendaActionPerformed(evt);
            }
        });

        LabelQuantidadeOleosVenda.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelQuantidadeOleosVenda.setText(bundle.getString("Comanda.LabelQuantidadeOleosVenda.text")); // NOI18N

        LabelEspeciePrecoVendaOleo.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        LabelEspeciePrecoVendaOleo.setText(bundle.getString("Comanda.LabelEspeciePrecoVendaOleo.text")); // NOI18N

        javax.swing.GroupLayout PainelCompraOleoLayout = new javax.swing.GroupLayout(PainelCompraOleo);
        PainelCompraOleo.setLayout(PainelCompraOleoLayout);
        PainelCompraOleoLayout.setHorizontalGroup(
            PainelCompraOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCompraOleoLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(LabelQuantidadeOleosVenda)
                .addGap(87, 87, 87)
                .addComponent(LabelEspeciePrecoVendaOleo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PainelCompraOleoLayout.createSequentialGroup()
                .addGroup(PainelCompraOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBoxOleo500Venda)
                    .addComponent(CheckBoxOleo1Venda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCompraOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InputQuantidadeOleo500Venda)
                    .addComponent(InputQuantidadeOleo1Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(PainelCompraOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InputPrecoOleo500Venda)
                    .addComponent(InputPrecoOleo1Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PainelCompraOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelCompraOleoLayout.createSequentialGroup()
                    .addGap(559, 559, 559)
                    .addGroup(PainelCompraOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelTotalPrecoVendaOleo)
                        .addComponent(InputTotalPrecoOleo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(50, Short.MAX_VALUE)))
        );
        PainelCompraOleoLayout.setVerticalGroup(
            PainelCompraOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCompraOleoLayout.createSequentialGroup()
                .addGroup(PainelCompraOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelQuantidadeOleosVenda)
                    .addComponent(LabelEspeciePrecoVendaOleo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCompraOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCompraOleoLayout.createSequentialGroup()
                        .addGroup(PainelCompraOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputQuantidadeOleo500Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckBoxOleo500Venda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCompraOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputQuantidadeOleo1Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckBoxOleo1Venda)))
                    .addGroup(PainelCompraOleoLayout.createSequentialGroup()
                        .addComponent(InputPrecoOleo500Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputPrecoOleo1Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(PainelCompraOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelCompraOleoLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(LabelTotalPrecoVendaOleo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(InputTotalPrecoOleo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );

        BotaoCalcular.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        BotaoCalcular.setText(bundle.getString("Comanda.BotaoCalcular.text")); // NOI18N
        BotaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCalcularActionPerformed(evt);
            }
        });

        BotaoNovo.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        BotaoNovo.setText(bundle.getString("Comanda.BotaoNovo.text")); // NOI18N
        BotaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoActionPerformed(evt);
            }
        });

        BotaoFexar.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        BotaoFexar.setText(bundle.getString("Comanda.BotaoFexar.text")); // NOI18N

        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BotaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(BotaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoFexar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCalcular)
                    .addComponent(BotaoNovo)
                    .addComponent(BotaoFexar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelPrecoCombustive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PainelPrecoOleo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PainelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PainelPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PainelCompraOleo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PainelAbastecimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelPrecoCombustive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelPrecoOleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(PainelCompraOleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addComponent(PainelAbastecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(403, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioGasAditivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioGasAditivadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioGasAditivadaActionPerformed

    private void RadioAlcoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAlcoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioAlcoolActionPerformed

    private void RadioGasComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioGasComumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioGasComumActionPerformed

    private void RadioPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioPrazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioPrazoActionPerformed

    private void InputDiasPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDiasPrazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDiasPrazoActionPerformed

    private void BotaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCalcularActionPerformed
        posto.getCombustivel(0).setValor(InputPrecoOleoDisel.getText());
        posto.getCombustivel(1).setValor(InputPrecoGasComum.getText());
        posto.getCombustivel(2).setValor(InputPrecoGasAditivada.getText());
        posto.getCombustivel(3).setValor(InputPrecoAlcool.getText());
        posto.getOleoMotor(0).setValor(InputPrecoOleo500.getText());
        posto.getOleoMotor(1).setValor(InputPrecoOleo1.getText());
        
        
    }//GEN-LAST:event_BotaoCalcularActionPerformed

    private void InputPrecoOleoDiselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPrecoOleoDiselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPrecoOleoDiselActionPerformed

    private void InputPrecoOleoDiselKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPrecoOleoDiselKeyTyped
            String caracteres="0987654321";
            if(!caracteres.contains(evt.getKeyChar()+"")){
                evt.consume();
            }
    }//GEN-LAST:event_InputPrecoOleoDiselKeyTyped

    private void InputPrecoGasComumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPrecoGasComumKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_InputPrecoGasComumKeyTyped

    private void InputPrecoGasAditivadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPrecoGasAditivadaKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_InputPrecoGasAditivadaKeyTyped

    private void InputPrecoAlcoolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPrecoAlcoolKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_InputPrecoAlcoolKeyTyped

    private void InputPrecoOleo500KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPrecoOleo500KeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_InputPrecoOleo500KeyTyped

    private void InputPrecoOleo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPrecoOleo1KeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_InputPrecoOleo1KeyTyped

    private void InputQuantidadeVendaCombustivelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputQuantidadeVendaCombustivelKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_InputQuantidadeVendaCombustivelKeyTyped

    private void InputValorTotalVendaCombustivelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputValorTotalVendaCombustivelKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_InputValorTotalVendaCombustivelKeyTyped

    private void InputQuantidadeOleo500VendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputQuantidadeOleo500VendaKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_InputQuantidadeOleo500VendaKeyTyped

    private void InputQuantidadeOleo1VendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputQuantidadeOleo1VendaKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_InputQuantidadeOleo1VendaKeyTyped

    private void InputDiasPrazoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputDiasPrazoKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_InputDiasPrazoKeyTyped

    private void CheckBoxOleo500VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxOleo500VendaActionPerformed
        (CheckBoxOleo500Venda ? InputQuantidadeOleo500Venda.setEnable(true) : InputQuantidadeOleo500Venda.setEnable(false));
    }//GEN-LAST:event_CheckBoxOleo500VendaActionPerformed

    private void InputQuantidadeOleo500VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputQuantidadeOleo500VendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputQuantidadeOleo500VendaActionPerformed

    private void CheckBoxOleo1VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxOleo1VendaActionPerformed
        (CheckBoxOleo500Venda ? InputQuantidadeOleo1Venda.setEnable(true) : InputQuantidadeOleo1Venda.setEnable(false));
    }//GEN-LAST:event_CheckBoxOleo1VendaActionPerformed

    private void BotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoActionPerformed
        InputPrecoOleoDisel.setText(posto.getCombustivel(0).getValor());
        InputPrecoGasComum.setText(posto.getCombustivel(1).getValor());
        InputPrecoGasAditivada.setText(posto.getCombustivel(2).getValor());
        InputPrecoAlcool.setText(posto.getCombustivel(3).getValor());
        InputPrecoOleo500.setText(posto.getOleoMotor(0).getValor());
        InputPrecoOleo1.setText(posto.getOleoMotor(1).getValor());
    }//GEN-LAST:event_BotaoNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
